### ISSUE TITLE
Add Board Jingle SFX When Equipped in Shop

### ISSUE THREAD

**Issue by Aegistus** [gmuGADIG/Gorilla-Grind#31]
Requirements:
- Add unique sound scriptable objects for each board jingle.
- Make the game play specific jingles whenever a board type is equipped in the shop.

Notes:
- The sound files are not currently in the project yet, so they will need to be retrieved from Sound Team (ask Xavier).
- In order to add a new Sound to the game, go to /Resources/Sounds/, right click->Create->Sound, name the Sound scriptable object, then add the imported sound files as Audio Variants.
- The sound can then be played in code using SoundManager.Instance.PlaySoundGlobal([soundID]). Get the soundID in Start() with SoundManager.Instance.GetSoundID([sound scriptable object name]).
- Talk to Joe for any questions on the sound system.

**Comment by Justin1L8** [comment]
Added the implementation to play the sounds. Just need someone to add the scriptable objects / sound files and set each shop item's `Equip Sound Name` field to the right sound.
