### ISSUE TITLE
movement glitches out on edge of map section

### ISSUE THREAD

**Issue by micycle8778** [gmuGADIG/Gorilla-Grind#7]

**Comment by RainbowAsteroids** [comment]
https://user-images.githubusercontent.com/29179327/231621226-0ba9a26e-c8da-41b8-9f51-af410efbb836.mp4

**Comment by micycle8778** [comment]
https://user-images.githubusercontent.com/29179327/231621392-ab544ccd-b50d-41ac-8449-1d1b7c100fee.mp4
