### ISSUE TITLE
Player can glitch through the ground

### ISSUE THREAD

**Issue by micycle8778** [gmuGADIG/Gorilla-Grind#71]
https://github.com/gmuGADIG/Gorilla-Grind/assets/29179327/7cc31d6c-bb86-4661-b2fb-b2e877903fd0

**Comment by micycle8778** [comment]
It looks like the bug is caused because `PlayerMovement.LandingCheck()` returns false when the player's Y velocity positive. That condition was originally there to prevent the player from snapping to the ground the second they hit it from below, but I don't know how I should change the condition to make it work better.
I also haven't seen a new ground edge that has two stories, so we could just remove the condition all together. ¯\\\_(ツ)_/¯

@Aegistus @Justin1L8

**Comment by Justin1L8** [comment]
Fixed in ParticlesAndCollisionFix 👍
